// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGiK_KszjFYGY-qlo-QqmfHj6DsdgbAI8',
    appId: '1:422309355739:web:412dce9cced4defe336cfe',
    messagingSenderId: '422309355739',
    projectId: 'aicharamaker',
    authDomain: 'aicharamaker.firebaseapp.com',
    storageBucket: 'aicharamaker.firebasestorage.app',
    measurementId: 'G-7VQ3R5BB5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFJ_pjQz96Gl3eKKhe28ybemrBdvm6w6w',
    appId: '1:422309355739:android:8691bbd78039e203336cfe',
    messagingSenderId: '422309355739',
    projectId: 'aicharamaker',
    storageBucket: 'aicharamaker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCox7Nr-5K7zLrEMb0vKO3ENYuA-iWldPM',
    appId: '1:422309355739:ios:f43f7449ece56278336cfe',
    messagingSenderId: '422309355739',
    projectId: 'aicharamaker',
    storageBucket: 'aicharamaker.firebasestorage.app',
    iosBundleId: 'com.example.aicharamaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCox7Nr-5K7zLrEMb0vKO3ENYuA-iWldPM',
    appId: '1:422309355739:ios:f43f7449ece56278336cfe',
    messagingSenderId: '422309355739',
    projectId: 'aicharamaker',
    storageBucket: 'aicharamaker.firebasestorage.app',
    iosBundleId: 'com.example.aicharamaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGiK_KszjFYGY-qlo-QqmfHj6DsdgbAI8',
    appId: '1:422309355739:web:dd7910e57b4e0ba9336cfe',
    messagingSenderId: '422309355739',
    projectId: 'aicharamaker',
    authDomain: 'aicharamaker.firebaseapp.com',
    storageBucket: 'aicharamaker.firebasestorage.app',
    measurementId: 'G-21GDS0FX71',
  );

}